// examples/solid-component-bundle/src/components/CounterButton/index.tsx
import type { Component } from 'solid-js';
import styles from './index.module.scss';

interface CounterButtonProps {
  onClick: () => void;
  label: string;
}

export const CounterButton: Component<CounterButtonProps> = (props) => (
  <button
    type="button"
    onClick={props.onClick}
    classList={{ 'counter-button': true, [styles.button]: true }}
  >
    {props.label}
  </button>
);

// examples/preact-component-bundle-false/src/components/CounterButton/index.tsx
import type { FunctionComponent } from 'preact';
import styles from './index.module.scss';

interface CounterButtonProps {
  onClick: () => void;
  label: string;
}

export const CounterButton: FunctionComponent<CounterButtonProps> = ({
  onClick,
  label,
}) => (
  <button type="button" className={styles.button} onClick={onClick}>
    {label}
  </button>
);
