// examples/solid-component-bundle/src/index.tsx
import type { Component } from 'solid-js';
import { CounterButton } from './components/CounterButton';
import './index.scss';
import { useCounter } from './useCounter';

export const Counter: Component = () => {
  const { count, increment, decrement } = useCounter();

  return (
    <div>
      <h1 class="counter-title">Solid</h1>
      <h2 class="counter-text">Counter: {count()}</h2>
      <CounterButton onClick={decrement} label="-" />
      <CounterButton onClick={increment} label="+" />
    </div>
  );
};

// examples/react-component-bundle/src/index.tsx
import React from 'react';
import { CounterButton } from './components/CounterButton/index';
import { useCounter } from './useCounter';
import './index.scss';

export const Counter: React.FC = () => {
  const { count, increment, decrement } = useCounter();

  return (
    <div>
      <h1 className="title" />
      <h2 className="counter-text">Counter: {count}</h2>
      <CounterButton onClick={decrement} label="-" />
      <CounterButton onClick={increment} label="+" />
    </div>
  );
};
