// examples/preact-component-bundle-false/src/useCounter.tsx
import { useState } from 'preact/hooks';

export const useCounter = (initialValue = 0) => {
  const [count, setCount] = useState(initialValue);

  const increment = () => setCount((prev) => prev + 1);
  const decrement = () => setCount((prev) => prev - 1);

  return { count, increment, decrement };
};

// examples/solid-component-bundle/src/useCounter.ts
import { createSignal } from 'solid-js';

export const useCounter = (initialValue = 0) => {
  const [count, setCount] = createSignal(initialValue);

  const increment = () => setCount((prev) => prev + 1);
  const decrement = () => setCount((prev) => prev - 1);

  return { count, increment, decrement };
};
