// packages/create-rslib/template-[react]-[vitest]-ts/src/Button.tsx
import React from 'react';
import './button.css';

interface ButtonProps {
  primary?: boolean;
  backgroundColor?: string;
  size?: 'small' | 'medium' | 'large';
  label: string;
  onClick?: () => void;
}

export const Button = ({
  primary = false,
  size = 'medium',
  backgroundColor,
  label,
  ...props
}: ButtonProps) => {
  const mode = primary ? 'demo-button--primary' : 'demo-button--secondary';
  return (
    <button
      type="button"
      className={['demo-button', `demo-button--${size}`, mode].join(' ')}
      style={{ backgroundColor }}
      {...props}
    >
      {label}
    </button>
  );
};

// packages/create-rslib/template-[vue]-[vitest]-js/src/Button.vue
<template>
  <button
    type="button"
    :class="['demo-button', `demo-button--${size}`, mode]"
    :style="{ backgroundColor }"
    @click="onClick"
  >
    {{ label }}
  </button>
</template>

<script>
import './button.css';

export default {
  name: 'Button',
  props: {
    primary: {
      type: Boolean,
      default: false,
    },
    backgroundColor: {
      type: String,
      default: undefined,
    },
    size: {
      type: String,
      default: 'medium',
      validator: (value) => ['small', 'medium', 'large'].includes(value),
    },
    label: {
      type: String,
      required: true,
    },
    onClick: {
      type: Function,
      default: undefined,
    },
  },
  computed: {
    mode() {
      return this.primary ? 'demo-button--primary' : 'demo-button--secondary';
    },
  },
};
</script>
