// packages/create-rslib/template-[vue]-[storybook,vitest]-ts/src/Button.vue
<script setup lang="ts">
import { computed } from 'vue';
import './style.css';

interface Props {
  primary?: boolean;
  backgroundColor?: string;
  size?: 'small' | 'medium' | 'large';
  label: string;
  onClick?: () => void;
}

const {
  primary = false,
  backgroundColor = undefined,
  size = 'medium',
  label,
  onClick = undefined,
} = defineProps<Props>();

const mode = computed(() =>
  primary ? 'demo-button--primary' : 'demo-button--secondary',
);
</script>

<template>
  <button
    type="button"
    :class="['demo-button', `demo-button--${size}`, mode]"
    :style="{ backgroundColor }"
    @click="onClick"
  >
    {{ label }}
  </button>
</template>

// packages/create-rslib/template-[react]-[vitest]-ts/src/Button.tsx
import React from 'react';
import './button.css';

interface ButtonProps {
  primary?: boolean;
  backgroundColor?: string;
  size?: 'small' | 'medium' | 'large';
  label: string;
  onClick?: () => void;
}

export const Button = ({
  primary = false,
  size = 'medium',
  backgroundColor,
  label,
  ...props
}: ButtonProps) => {
  const mode = primary ? 'demo-button--primary' : 'demo-button--secondary';
  return (
    <button
      type="button"
      className={['demo-button', `demo-button--${size}`, mode].join(' ')}
      style={{ backgroundColor }}
      {...props}
    >
      {label}
    </button>
  );
};
